#!/usr/bin/env bash

# Generates a script that assigns all IPs and routes that are on the currently running system.
# The script is a bash script which executes `ip a a` and `ip r a`.
# It works for IPv4 and IPv6

set -e
set -u
set -o pipefail

echo '#!/usr/bin/env bash
set -x
set +e
'

doIp() {
	echo "ip a a ${1} dev ${2}"
}

doRoute() {
	echo "ip r a ${1}"
}

interface=''
while IFS= read -r line; do
	case "${line}" in
		'    '*)
			[ "${interface:-}" = lo ] && continue
			# This may be an IP
			case "${line}" in
				'    inet'*)
					doIp "$(echo "${line}" | cut -d' ' -f6)" "${interface}"
					;;
			esac
			;;
		*)
			interface="$(echo "${line}" | cut -d':' -f2 | xargs)"
			;;
	esac
done < <(ip a)

while IFS= read -r line; do
	doRoute "${line}"
done < <(ip r; ip -6 r)
